language: perl
perl:
  - 5.14
  - 5.12
  - "5.10"
  - 5.8
before_install:
  - perlbrew install-cpanm -f
install:
  - cpanm --install-args='INSTALLDIRS=perl' ExtUtils::MakeMaker
  - cpanm -nq --installdeps --with-develop --with-recommends --with-suggests .
script:
  - prove -lr xt -j9
sudo: false
