language: perl
perl:
  - 5.14
  - 5.12
  - "5.10"
  - 5.8
before_install:
  - perlbrew install-cpanm -f
install:
  - cpanm --configure-args=INSTALLDIRS=perl ExtUtils::MakeMaker@6.59
  - cpanm -nq --installdeps --with-develop --with-recommends --with-suggests .
  - perl -MExtUtils::MakeMaker -le 'print $INC{"ExtUtils/MakeMaker.pm"}; print $ExtUtils::MakeMaker::VERSION'
  - perl -Mlib -le 'BEGIN{ no lib grep { m{/site_perl/} } @INC; } use ExtUtils::MakeMaker; print $ExtUtils::MakeMaker::VERSION; print $INC{"ExtUtils/MakeMaker.pm"}'
script:
  - prove -lr xt -j9
sudo: false
